before_install: cd tasks
language: node_js
node_js:
  - 8.11.3
cache:
  directories:
    -node_modules
sudo: required
node_js:
  - "lts/*"
install:
  - npm install -g codecov
after_sucesss:
  - npm run coverage
