before_install: cd tasks
language: node_js
sudo: false
node_js:
  - "lts/*"
install:
  - npm install -g codecov
script:
  - nyc ./node_modules/mocha/bin/_mocha --timeout 10000 --recursive --reporter lcovonly -- -R spec
  - codecov