before_install: 
   - cd tasks
   - npm install -g npm
language: node_js
node_js:
  - 8.11.3
sudo: false
node_js:
  - "lts/*"
install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm install -g mocha
after_sucess:
  - npm run coverage
