before_install: cd tasks
language: node_js
sudo: false
node_js:
  - "lts/*"
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov