before_install: cd tasks
language: node_js
node_js:
  - 8.11.3
dist: trusty
cache:
  directories:
    -node_modules
sudo: required
node_js:
  - "lts/*"
install:
  - npm install -g codecov
  - npm install -g nyc
after_sucesss:
  - npm run coverage
